### ISSUE TITLE
bug: Put a note as shown below or better way

### ISSUE THREAD

**Issue by Sampath-Lokuge** [robingenz/capacitor-firebase-authentication-demo#162]
Hi,

Since most of the Ionic apps are native apps we do not need the `initializeApp` workflow completely. So it would be great if you'll put some sort of note there. Otherwise, most of the devs will add Web things also to their native apps. i.e. Firebase configuration on environment files and unnecessary imports like so `import { initializeApp } from '@firebase/app';` and its code and etc. i.e. copy/paste from this project. Thanks!

```
 public async initialize(): Promise<void> {
    if (this.platform.is('capacitor')) {
      return;
    }
    initializeApp(environment.firebase);//only for Web Auth. i.e. no need for native only apps
  }
```

**Comment by robingenz** [comment]
Good point! I will add a note.

**Comment by robingenz** [comment]
This is also related to #2

**Comment by Sampath-Lokuge** [comment]
Ok sure. Great!
