### ISSUE TITLE
bug: Google Login not working after releasing the .aab to Play Store ( Internal Testing )

### ISSUE THREAD

**Issue by ShriMVarkhedi** [robingenz/capacitor-firebase-authentication-demo#220]
Even after configuring the SHA - 1 fingerprint of both Release Key and App signing from play store, Google sign in not working.

**Comment by robingenz** [comment]
What is the error message?

**Comment by ShriMVarkhedi** [comment]
Unable to get the logs. But works fine in debug mode.

**Comment by robingenz** [comment]
No, this does not help.
If it works in debug mode, the problem is not with the plugin but with the configuration.
In most cases it is due to a SHA-1 that is not found at first. I recommend you to double check everything.

I'm closing this issue because it's not a problem with this demo app.

**Comment by ShriMVarkhedi** [comment]
@robingenz I agree that it is not with the plugin. Required your help here to figure out what is the issue

**Comment by robingenz** [comment]
As i said, please double check your configuration. That must be the problem. Check if Google Play Store signs your app  with a different SHA-1.
