### ISSUE TITLE
bug: [Capacitor] [IOS] Cannot request OTP when use FirebaseAuthentication.signInWithPhoneNumber

### ISSUE THREAD

**Issue by meawiey** [robingenz/capacitor-firebase-authentication-demo#226]
**Describe the bug**
I found error "[error] - SMS not sent  {"code":"auth/internal-error","customData":{},"name":"FirebaseError"}" when use ionic capacitor firebase in platform IOS 

**Setup Project & Reproduce**
1.  Add package   https://github.com/firebase/firebase-ios-sdk.git in x code
<img width="1087" alt="image" src="https://github.com/robingenz/capacitor-firebase-authentication-demo/assets/17870679/995bb7ee-4297-4040-8971-1c98252ca17e">

2. initializeApp(firebaseConfig); in app.component.ts
3. signInAnonymously() in app.component.ts success and receive token firebase
4. Request OTP and found error "[error] - SMS not sent  {"code":"auth/internal-error","customData":{},"name":"FirebaseError"}"

**Expected behavior**
Can use signInWithPhoneNumber and verify OTP 

**Screenshots**
<img width="1404" alt="image" src="https://github.com/robingenz/capacitor-firebase-authentication-demo/assets/17870679/b2b9b963-bc5d-48f3-b76f-94f7df320d4c">

**Smartphone (please complete the following information):**

- OS: IOS 17
- Simulator: iPhone 15 Pro
- Version [7

**Additional context**
git repo :> https://github.com/meawiey/capacitor_firebase

**Comment by robingenz** [comment]
You should not add the Firebase swift package manually. The Firebase SDK is already installed.

**Comment by meawiey** [comment]
I already remove package firebase 
<img width="1081" alt="image" src="https://github.com/robingenz/capacitor-firebase-authentication-demo/assets/17870679/50c34355-652b-4902-a142-32d0f39900de">

after I build and request otp I found new error "[error] - SMS not sent  {"code":"auth/internal-error","customData":{},"name":"FirebaseError"}"

<img width="1408" alt="image" src="https://github.com/robingenz/capacitor-firebase-authentication-demo/assets/17870679/db474d43-d2d2-4b52-8378-3b20aed918c5">

**Comment by robingenz** [comment]
I have just noticed that this issue is not about this project but occurs in your own app. For this reason, I am closing this issue.
Unfortunately, I have no idea what the error is. The error message itself is not very descriptive. Make sure that the phone number is formatted correctly. In addition, I would use a fictitious phone number for testing to narrow down the problem (see https://firebase.google.com/docs/auth/android/phone-auth#test-with-fictional-phone-numbers).
