### ISSUE TITLE
bug:  Does not build on Android

### ISSUE THREAD

**Issue by andreibaca** [robingenz/capacitor-firebase-authentication-demo#62]
**Describe the bug**
Can not build for Android - keystore.properties file is missing
~.../capacitor-firebase-authentication-demo/android/keystore.properties (No such file or directory)

**To Reproduce**
Follow the instructions in the readme + 'npm run build'

**Expected behavior**
Run the project and see the capacitor-firebase-authentication plugin in action

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version 18.04

**Comment by robingenz** [comment]
Hi @andreibaca,
thank you for your request.
The setup documentation is not ready yet and some information is missing.
In this case you need a file `android/keystore.properties` with the following content:
```
storePassword=YOUR_STORE_PASSWORD
keyPassword=YOUR_KEY_PASSWORD
keyAlias=YOUR_KEY_ALIAS
storeFile=YOUR_STORE_FILE
```
Read more about this [here](https://stackoverflow.com/a/49022618).
